### PR TITLE
Feature/error reversion

### PR DESCRIPTION
**Pull request by haydenmcp**
@stramel

### CODE REVIEW

**Comment by haydenmcp** [comment]
@stramel

**Comment by haydenmcp** [comment]
@admwx7 @stramel This change allows promo editor to clear all errors when desired.

**Review by admwx7 — CHANGES_REQUESTED** [review]
Per my messages in slack:

amurdock [3:36 PM] 
`__revertErrorMessage` doesn't seem to be utilizing `errorMessageAttribute`.
Neither should utilize `invalidAttr` since invalid is invalid, shouldn't let them mess with that one.
The logic in setting errors is supposed to empty out the errors array.
`__revertErrorMessage` already does all of that logic, you just need each element to fire an `invalid-changed` event to set invalid to false, which would collapse your logic down to:
```clearErrors(form = this.form) {
  const fields = form.querySelectorAll('[invalid]');
  fields.forEach((field) => {
    field.removeAttribute('invalid');
  });
}
```
With that all fields that are polymer elements (which is required to consumed the errorMessage that was set on it) will fire an invalid-changed event which should call the logic that's already assigned to it.  The only outliers are any elements that have invalid set as a readonly function, not sure what all that applies to but I guess we could dispatch an `invalid-changed` event from the elements just to be safe?
[3:37] 
Also you don't need to use `bind` on that function since it's not an event listener anywhere.
[3:39] 
Maybe also throw a `field.invalid = false` in there before the removeAttribute for completeness?

**Review by stramel — APPROVED** [review]

**Review by admwx7 — APPROVED** [review]

**Comment by stramel** [comment]
@haydenmcp or someone.... can you either merge or close this? It's rather annoying sitting in my list

**Comment by stramel** [comment]
Thanks @jay8t6

**Pull request closed without merging**
